# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Test Automatico

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
     - name: Scarica il codice dalla repository
       uses: actions/checkout@v4
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
     - name: Compilazione ed esecuzione dei test
       run: mvn clean install

     - name: Pubblica i report su GitHub
       uses: dorny/test-reporter@v1
       if: always() #esegue sempre i test anche se falliscono
       with:
        name: Risultati JUnit
        path: target/surefire-reports/*xml #Mette il report nel percorso standard
        reporter: java-junit

