name: Java Test Automatico (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest # i test verranno eseguiti su windows

    permissions:
      checks: write
      contents: read
      actions: read

    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #Permette a SonarCloud di leggere la cronologia git
      #imposta java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      #configurazione database h2 per testing
      - name: Configura database.properties (H2 In-Memory)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path src/test/resources
          $content = "db.url=jdbc:h2:mem:fantamaster_test_db;DB_CLOSE_DELAY=-1;MODE=MySQL`ndb.username=sa`ndb.password="
          $content | Out-File -FilePath src/test/resources/database.properties -Encoding utf8
        working-directory: ./Java_Project/fantamaster 

      - name: Esecuzione test & analisi di SonarCloud
        run: mvn clean verify "-Dmaven.test.failure.ignore=true" "-Dsonar.projectKey=03Maikol33_FantaMaster-CAMB" "-Dsonar.organization=fantamaster-camb" "-Dsonar.host.url=https://sonarcloud.io" "-Dsonar.token=${{ secrets.SONAR_TOKEN }}"
        working-directory: ./Java_Project/fantamaster
        env:
          JAVA_TOOL_OPTIONS: "-Djava.awt.headless=false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Pubblica i report JUnit
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Risultati JUnit
          path: Java_Project/fantamaster/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false 

      - name: Carica Report Coverage (HTML)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-copertura-jacoco
          path: Java_Project/fantamaster/target/site/jacoco/
